[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True

# SQLAlchemy 插件
plugins = sqlalchemy.ext.mypy.plugin

# 忽略特定错误
[mypy-app.models.schemas.*]
ignore_errors = True
